## Clock signal
set_property -dict { PACKAGE_PIN W5   IOSTANDARD LVCMOS33 } [get_ports clk_in1]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk_in1]

## LEDs
set_property PACKAGE_PIN U16 [get_ports {dato_pc[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dato_pc[0]}]
set_property PACKAGE_PIN E19 [get_ports {dato_pc[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dato_pc[1]}]
set_property PACKAGE_PIN U19 [get_ports {dato_pc[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dato_pc[2]}]
set_property PACKAGE_PIN V19 [get_ports {dato_pc[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dato_pc[3]}]
set_property PACKAGE_PIN W18 [get_ports {dato_pc[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dato_pc[4]}]
set_property PACKAGE_PIN U15 [get_ports {dato_pc[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dato_pc[5]}]
set_property PACKAGE_PIN U14 [get_ports {dato_pc[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dato_pc[6]}]
set_property PACKAGE_PIN V14 [get_ports {dato_pc[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {dato_pc[7]}]
	
## Switches
set_property PACKAGE_PIN V17 [get_ports {sw_pi[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_pi[0]}]
set_property PACKAGE_PIN V16 [get_ports {sw_pi[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_pi[1]}]
set_property PACKAGE_PIN W16 [get_ports {sw_pi[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_pi[2]}]
set_property PACKAGE_PIN W17 [get_ports {sw_pi[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_pi[3]}]
set_property PACKAGE_PIN W15 [get_ports {sw_pi[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_pi[4]}]
set_property PACKAGE_PIN V15 [get_ports {sw_pi[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_pi[5]}]
set_property PACKAGE_PIN W14 [get_ports {sw_pi[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_pi[6]}]
set_property PACKAGE_PIN W13 [get_ports {sw_pi[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw_pi[7]}]
	
set_property PACKAGE_PIN R2 [get_ports {inicio_pi}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {inicio_pi}]
	
##Buttons
#set_property PACKAGE_PIN U18 [get_ports btnC]						
	#set_property IOSTANDARD LVCMOS33 [get_ports btnC]
set_property PACKAGE_PIN T18 [get_ports enviar_dato_pi]						
	set_property IOSTANDARD LVCMOS33 [get_ports enviar_dato_pi]
#set_property PACKAGE_PIN W19 [get_ports btnL]						
	#set_property IOSTANDARD LVCMOS33 [get_ports btnL]
#set_property PACKAGE_PIN T17 [get_ports btnR]						
	#set_property IOSTANDARD LVCMOS33 [get_ports btnR]
set_property PACKAGE_PIN U17 [get_ports reset_pi]						
	set_property IOSTANDARD LVCMOS33 [get_ports reset_pi]
	
##USB-RS232 Interface
set_property PACKAGE_PIN B18 [get_ports rx]
    set_property IOSTANDARD LVCMOS33 [get_ports rx]  
set_property PACKAGE_PIN A18 [get_ports tx]
    set_property IOSTANDARD LVCMOS33 [get_ports tx]